"""add_domain_events_and_transversal_notes

Revision ID: 172484df6b1e
Revises: a1b8648031df
Create Date: 2026-02-09 20:27:41.803905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '172484df6b1e'
down_revision: Union[str, Sequence[str], None] = 'a1b8648031df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_events_actor_user_id'), 'domain_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_domain_events_entity_id'), 'domain_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_domain_events_entity_type'), 'domain_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_domain_events_event_type'), 'domain_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_domain_events_occurred_at'), 'domain_events', ['occurred_at'], unique=False)
    op.create_table('client_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_notes_author_user_id'), 'client_notes', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_client_notes_client_id'), 'client_notes', ['client_id'], unique=False)
    op.create_table('property_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_notes_author_user_id'), 'property_notes', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_property_notes_property_id'), 'property_notes', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_notes_property_id'), table_name='property_notes')
    op.drop_index(op.f('ix_property_notes_author_user_id'), table_name='property_notes')
    op.drop_table('property_notes')
    op.drop_index(op.f('ix_client_notes_client_id'), table_name='client_notes')
    op.drop_index(op.f('ix_client_notes_author_user_id'), table_name='client_notes')
    op.drop_table('client_notes')
    op.drop_index(op.f('ix_domain_events_occurred_at'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_event_type'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_entity_type'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_entity_id'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_actor_user_id'), table_name='domain_events')
    op.drop_table('domain_events')
    # ### end Alembic commands ###
