"""extract_visit_notes_table

Revision ID: 1c9da1823f34
Revises: 172484df6b1e
Create Date: 2026-02-09 20:34:42.446906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9da1823f34'
down_revision: Union[str, Sequence[str], None] = '172484df6b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_notes_author_user_id'), 'visit_notes', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_visit_notes_visit_id'), 'visit_notes', ['visit_id'], unique=False)
    op.drop_column('visits', 'post_visit_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('post_visit_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_visit_notes_visit_id'), table_name='visit_notes')
    op.drop_index(op.f('ix_visit_notes_author_user_id'), table_name='visit_notes')
    op.drop_table('visit_notes')
    # ### end Alembic commands ###
