"""Initial_migration

Revision ID: 467f50c9de1a
Revises: 
Create Date: 2026-02-06 19:05:58.358139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467f50c9de1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'AGENT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('BUYER', 'TENANT', 'OWNER', name='clienttype'), nullable=False),
    sa.Column('responsible_agent_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['responsible_agent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_is_active'), 'clients', ['is_active'], unique=False)
    op.create_index(op.f('ix_clients_responsible_agent_id'), 'clients', ['responsible_agent_id'], unique=False)
    op.create_index(op.f('ix_clients_type'), 'clients', ['type'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address_line1', sa.String(), nullable=False),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('sqm', sa.Integer(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'SOLD', 'RENTED', name='propertystatus'), nullable=False),
    sa.Column('owner_client_id', sa.UUID(), nullable=False),
    sa.Column('captor_agent_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('public_description', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_currency', sa.String(length=3), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['captor_agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_captor_agent_id'), 'properties', ['captor_agent_id'], unique=False)
    op.create_index(op.f('ix_properties_owner_client_id'), 'properties', ['owner_client_id'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_owner_client_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_captor_agent_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_clients_type'), table_name='clients')
    op.drop_index(op.f('ix_clients_responsible_agent_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_is_active'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
