"""add_operations_and_trazability

Revision ID: 690be2b8512d
Revises: 700155108806
Create Date: 2026-02-09 19:29:14.596258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690be2b8512d'
down_revision: Union[str, Sequence[str], None] = '700155108806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('SALE', 'RENT', name='operationtype'), nullable=False),
    sa.Column('status', sa.Enum('INTEREST', 'NEGOTIATION', 'RESERVED', 'CLOSED', 'CANCELLED', name='operationstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_agent_id'), 'operations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_operations_client_id'), 'operations', ['client_id'], unique=False)
    op.create_index(op.f('ix_operations_property_id'), 'operations', ['property_id'], unique=False)
    op.create_index(op.f('ix_operations_status'), 'operations', ['status'], unique=False)
    op.create_table('operation_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_notes_author_user_id'), 'operation_notes', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_operation_notes_operation_id'), 'operation_notes', ['operation_id'], unique=False)
    op.create_table('operation_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('INTEREST', 'NEGOTIATION', 'RESERVED', 'CLOSED', 'CANCELLED', name='operationstatus'), nullable=False),
    sa.Column('to_status', sa.Enum('INTEREST', 'NEGOTIATION', 'RESERVED', 'CLOSED', 'CANCELLED', name='operationstatus'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_status_history_changed_by_user_id'), 'operation_status_history', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_operation_status_history_operation_id'), 'operation_status_history', ['operation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_status_history_operation_id'), table_name='operation_status_history')
    op.drop_index(op.f('ix_operation_status_history_changed_by_user_id'), table_name='operation_status_history')
    op.drop_table('operation_status_history')
    op.drop_index(op.f('ix_operation_notes_operation_id'), table_name='operation_notes')
    op.drop_index(op.f('ix_operation_notes_author_user_id'), table_name='operation_notes')
    op.drop_table('operation_notes')
    op.drop_index(op.f('ix_operations_status'), table_name='operations')
    op.drop_index(op.f('ix_operations_property_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_client_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_agent_id'), table_name='operations')
    op.drop_table('operations')
    # ### end Alembic commands ###
