"""add_baths_to_property

Revision ID: 78c5390ffb93
Revises: bf393330bd14
Create Date: 2026-02-17 23:04:57.240714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c5390ffb93'
down_revision: Union[str, Sequence[str], None] = 'bf393330bd14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('properties')]
    if 'baths' not in columns:
        op.add_column('properties', sa.Column('baths', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'baths')
    # ### end Alembic commands ###
