"""add_property_is_featured

Revision ID: 86d85ae9c2d4
Revises: aac78c933f3a
Create Date: 2026-02-14 20:39:46.302578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d85ae9c2d4'
down_revision: Union[str, Sequence[str], None] = 'aac78c933f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'is_featured')
    # ### end Alembic commands ###
