"""add_index_to_user_full_name

Revision ID: 9ebf73da517f
Revises: 59f0000e3fff
Create Date: 2026-02-09 19:53:43.647318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ebf73da517f'
down_revision: Union[str, Sequence[str], None] = '59f0000e3fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    # ### end Alembic commands ###
