"""add_calendar_event_composite_index

Revision ID: a1b8648031df
Revises: 70797025b962
Create Date: 2026-02-09 20:12:06.362950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b8648031df'
down_revision: Union[str, Sequence[str], None] = '70797025b962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_calendar_events_agent_starts_at', 'calendar_events', ['agent_id', 'starts_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_calendar_events_agent_starts_at', table_name='calendar_events')
    # ### end Alembic commands ###
