"""Add property status history

Revision ID: aac78c933f3a
Revises: b3f4a5c6d7e8
Create Date: 2026-02-13 19:37:26.233889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'aac78c933f3a'
down_revision: Union[str, Sequence[str], None] = 'b3f4a5c6d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('from_status', postgresql.ENUM(name='propertystatus', create_type=False), nullable=True),
    sa.Column('to_status', postgresql.ENUM(name='propertystatus', create_type=False), nullable=False),
    sa.Column('from_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('to_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_status_history_changed_by_user_id'), 'property_status_history', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_property_status_history_property_id'), 'property_status_history', ['property_id'], unique=False)
    op.drop_index(op.f('ix_properties_showcase_city'), table_name='properties')
    op.drop_index(op.f('ix_properties_showcase_filters'), table_name='properties')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_properties_showcase_filters'), 'properties', ['is_published', 'status', 'price_amount', 'sqm', 'rooms'], unique=False)
    op.create_index(op.f('ix_properties_showcase_city'), 'properties', ['is_published', 'status', 'city'], unique=False)
    op.drop_index(op.f('ix_property_status_history_property_id'), table_name='property_status_history')
    op.drop_index(op.f('ix_property_status_history_changed_by_user_id'), table_name='property_status_history')
    op.drop_table('property_status_history')
    # ### end Alembic commands ###
