"""sync_missing_fields

Revision ID: d3d6fe7a1cb1
Revises: 78c5390ffb93
Create Date: 2026-02-17 23:16:25.189396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d6fe7a1cb1'
down_revision: Union[str, Sequence[str], None] = '78c5390ffb93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Lógica para sincronizar campos en 'properties'
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('properties')]
    
    # 1. Definir tipos Enum (si no existen se crearán automáticamente por SQLAlchemy o fallará con gracia)
    # Nota: Alembic no soporta bien CREATE TYPE IF NOT EXISTS de forma nativa sin extensiones, 
    # pero para PostgreSQL podemos usar SQL directo si es necesario.
    
    if 'property_type' not in columns:
        op.add_column('properties', sa.Column('property_type', sa.Enum('APARTMENT', 'HOUSE', 'OFFICE', 'LAND', name='propertytype'), server_default='APARTMENT', nullable=False))
        op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)

    if 'operation_type' not in columns:
        op.add_column('properties', sa.Column('operation_type', sa.Enum('SALE', 'RENT', name='operationtype'), server_default='SALE', nullable=False))
        op.create_index(op.f('ix_properties_operation_type'), 'properties', ['operation_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_operation_type'), table_name='properties')
    op.drop_column('properties', 'operation_type')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_column('properties', 'property_type')
    # ### end Alembic commands ###
