"""sync_missing_fields

Revision ID: d3d6fe7a1cb1
Revises: 78c5390ffb93
Create Date: 2026-02-17 23:16:25.189396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3d6fe7a1cb1'
down_revision: Union[str, Sequence[str], None] = '78c5390ffb93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Lógica para sincronizar campos en 'properties'
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('properties')]
    
    # Crear tipos ENUM en PostgreSQL si no existen
    # Esto es crítico para evitar el error "type does not exist"
    if conn.dialect.name == 'postgresql':
        # Verificar y crear 'propertytype'
        type_exists = conn.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'propertytype'")).scalar()
        if not type_exists:
            op.execute("CREATE TYPE propertytype AS ENUM ('HOUSE', 'APARTMENT', 'OFFICE', 'LAND')")
            
        # Verificar y crear 'operationtype'
        type_exists = conn.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'operationtype'")).scalar()
        if not type_exists:
            op.execute("CREATE TYPE operationtype AS ENUM ('SALE', 'RENT')")
    
    if 'property_type' not in columns:
        # Usamos el nombre del tipo creado arriba
        op.add_column('properties', sa.Column('property_type', sa.Enum('HOUSE', 'APARTMENT', 'OFFICE', 'LAND', name='propertytype'), server_default='APARTMENT', nullable=False))
        op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)

    if 'operation_type' not in columns:
        op.add_column('properties', sa.Column('operation_type', sa.Enum('SALE', 'RENT', name='operationtype'), server_default='SALE', nullable=False))
        op.create_index(op.f('ix_properties_operation_type'), 'properties', ['operation_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_operation_type'), table_name='properties')
    op.drop_column('properties', 'operation_type')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_column('properties', 'property_type')
    # ### end Alembic commands ###
